# BEGIN_KITTY_FONTS
font_family      family="0xProto Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13
# END_KITTY_FONTS

# BEGIN_KITTY_CURSOR
cursor_shape block
# END_KITTY_CURSOR


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
#
# Open URL modifiers
open_url_modifiers ctrl
# END Open URL modifiers
